// <auto-generated />
using System;
using ChungKhoanASPDotNetCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChungKhoanASPDotNetCore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220417060721_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ChungKhoanASPDotNetCore.Entities.BangGiaTrucTuyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double?>("GiaBan1")
                        .HasColumnType("float");

                    b.Property<double?>("GiaBan2")
                        .HasColumnType("float");

                    b.Property<double?>("GiaBan3")
                        .HasColumnType("float");

                    b.Property<double?>("GiaKhop")
                        .HasColumnType("float");

                    b.Property<double?>("GiaMua1")
                        .HasColumnType("float");

                    b.Property<double?>("GiaMua2")
                        .HasColumnType("float");

                    b.Property<double?>("GiaMua3")
                        .HasColumnType("float");

                    b.Property<string>("MaCK")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("SoLuongBan1")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongBan2")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongBan3")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongKhop")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongMua1")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongMua2")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongMua3")
                        .HasColumnType("int");

                    b.Property<int?>("TongSo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaCK")
                        .IsUnique()
                        .HasFilter("[MaCK] IS NOT NULL");

                    b.ToTable("BangGiaTrucTuyen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaCK = "AAA"
                        },
                        new
                        {
                            Id = 2,
                            MaCK = "BBB"
                        },
                        new
                        {
                            Id = 3,
                            MaCK = "CCC"
                        });
                });

            modelBuilder.Entity("ChungKhoanASPDotNetCore.Entities.History", b =>
                {
                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Script")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FileName");

                    b.ToTable("_History");
                });

            modelBuilder.Entity("ChungKhoanASPDotNetCore.Entities.LenhDat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("GiaDat")
                        .HasColumnType("float");

                    b.Property<bool>("LoaiGiaoDich")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiLenh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaCK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LenhDat");
                });

            modelBuilder.Entity("ChungKhoanASPDotNetCore.Entities.LenhKhop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("GiaKhop")
                        .HasColumnType("float");

                    b.Property<int>("IdLenhDat")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayKhop")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuongKhop")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdLenhDat");

                    b.ToTable("LenhKhop");
                });

            modelBuilder.Entity("ChungKhoanASPDotNetCore.Entities.LenhKhop", b =>
                {
                    b.HasOne("ChungKhoanASPDotNetCore.Entities.LenhDat", "LenhDat")
                        .WithMany("LenhKhops")
                        .HasForeignKey("IdLenhDat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LenhDat");
                });

            modelBuilder.Entity("ChungKhoanASPDotNetCore.Entities.LenhDat", b =>
                {
                    b.Navigation("LenhKhops");
                });
#pragma warning restore 612, 618
        }
    }
}
